steps:
  - label: ":docker: build dev image"
    command: .buildkite/steps/build.sh

  - wait

  - label: ":partyparrot: deploy to staging"
    command: "ansible-playbook -i \"$SECRET_STAGE_SERVER_IP,\" -e \"deploy_tag=dev-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER\" playbooks/deploy.yaml --vault-password-file ~/vault_pass --private-key ~/.ssh/id_ed25519_io_runner"
  
  - wait

  - block: "Release?"
    prompt: "Deploy $BUILDKITE_TAG to production?"

  - wait

  - label: ":docker: release image to docker hub"
    command: .buildkite/steps/release-image.sh

  - wait

  - label: ":rocket: deploy to prod"
    command: "ansible-playbook -i \"$SECRET_PROD_SERVER_IP,\" --tags fast -e \"deploy_tag=$BUILDKITE_TAG\" playbooks/deploy.yaml --vault-password-file ~/vault_pass --private-key ~/.ssh/id_ed25519_io_runner"
